desafio_inoa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stock_users/', include('stock_users.urls')), 
    path('stocks/', include('stocks.urls')), 
    path('users/', include('users.urls')),
]

stock_users/urls.py
# stocks/urls.py
from django.urls import path
from .views import UserStocksView

app_name = 'stock_users'

urlpatterns = [
    path('<int:user_id>/', UserStocksView.as_view(), name='stock_users'),
    path('delete/', UserStocksView.as_view(), name='delete'),
    path('update/', UserStocksView.as_view(), name='update'),
]

stocks/urls.py
# stocks/urls.py
from django.urls import path
from .views import StocksListView

app_name = 'stocks'

urlpatterns = [
    path('', StocksListView.as_view(), name='index'),
]

users/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView, CustomRegistrationView, LogoutView

app_name = 'users'

urlpatterns = [
    path('', views.UsersListView.as_view(), name='users_list'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', CustomRegistrationView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

stock_users/models.py
from django.db import models
from users.models import User
from stocks.models import Stock
from django.utils import timezone

class StockUser(models.Model):
    close = models.DecimalField(max_digits=10, decimal_places=8)
    selling_price = models.DecimalField(max_digits=10, decimal_places=2)
    buying_price = models.DecimalField(max_digits=10, decimal_places=2)
    is_notifying = models.IntegerField()
    update_period = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    last_price_update = models.DateTimeField(default=timezone.now)

stocks/models.py
from django.db import models

class Stock(models.Model):
    stock = models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    logo = models.URLField()
    sector = models.CharField(max_length=100)

    def __str__(self):
        return self.stock

users/models.py
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class UserRegisterForm(UserCreationForm):
  email = forms.EmailField()

  class Meta:
      model = get_user_model()
      fields = ['username', 'email', 'password1', 'password2']

stock_users/views.py
from django.shortcuts import render
from django.views import View
from users.models import User
from stock_users.models import StockUser
from django.shortcuts import render
from decimal import Decimal
from django.http import HttpResponseRedirect
from django.urls import reverse


class UserStocksView(View):
    def get(self, request, user_id):

        user = request.user

        if not user.is_authenticated:
             return HttpResponseRedirect(reverse('users:login'))

        try:
            user = User.objects.get(pk=user_id)
            stock_users = StockUser.objects.filter(user_id=user_id)
            
            return render(request, 'stock_users/index.html', {'user': user, 'stocks': stock_users})
        except User.DoesNotExist:
            return render(request, 'user_not_found.html')
        
    def post(self, request):
            
            updated_stock_user_id = request.POST.get('updated_stock_user_id')

            if(updated_stock_user_id):
                 
                stock_user = StockUser.objects.get(pk=updated_stock_user_id)

                selling_price = request.POST.get('selling_price')
                buying_price = request.POST.get('buying_price')
                is_notifying = request.POST.get('is_notifying')
                update_period = request.POST.get('update_period')

                selling_price = Decimal(selling_price.replace(".", "").replace(",", "."))
                buying_price = Decimal(buying_price.replace(".", "").replace(",", "."))

                stock_user.selling_price = selling_price
                stock_user.buying_price = buying_price
                stock_user.is_notifying = is_notifying
                stock_user.update_period = update_period
                stock_user.save()

                return HttpResponseRedirect(reverse('stock_users:stock_users', args=[stock_user.user.id]))

            else:
                stock_user_id = request.POST.get('stock_user')
                stock_user = StockUser.objects.get(pk=stock_user_id)
                stock_user.delete()
                
                return HttpResponseRedirect(reverse('stock_users:stock_users', args=[stock_user.user.id]))

stocks/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Stock
from stock_users.models import StockUser
from users.models import User
import requests
from django.db.models import Subquery
from decimal import Decimal
from django.http import HttpResponseRedirect
from django.urls import reverse

class StocksListView(ListView):
    
    def get(self, request): 
        try:
            user = User.objects.get(pk=request.user.id)

            subquery = StockUser.objects.filter(user=user).values('stock_id')

            stocks = Stock.objects.exclude(pk__in=Subquery(subquery))
            
            return render(request, 'stocks/index.html', {'stocks': stocks})
        except User.DoesNotExist:
            return HttpResponseRedirect(reverse('users:login'))
    
    def post(self, request):

        user = User.objects.get(pk=request.user.id)
        subquery = StockUser.objects.filter(user=user).values('stock_id')
        stocks = Stock.objects.exclude(pk__in=Subquery(subquery))

        stock = request.POST.get('stock')
        selling_price = request.POST.get('selling_price')
        buying_price = request.POST.get('buying_price')
        is_notifying = request.POST.get('is_notifying')
        update_period = request.POST.get('update_period')
        stock = request.POST.get('stock')

        selling_price = Decimal(selling_price.replace(".", "").replace(",", "."))
        buying_price = Decimal(buying_price.replace(".", "").replace(",", "."))

        user_instance = User.objects.get(pk=request.user.id)
        stock_instance = Stock.objects.get(stock=stock)

        api_url = "https://brapi.dev/api/quote/list?sortBy=close&sortOrder=desc&limit=10&search={}".format(stock)
        
        try:
            response = requests.get(api_url)
            data = response.json()

            if(len(data['stocks']) < 1):
                raise Exception("A ação não está disponível no momento. Tente novamente mais tarde.")

            model_data = {
                "close": data['stocks'][0]['close'] if data['stocks'][0]['close'] else 0,
                "selling_price": selling_price, 
                "buying_price": buying_price,
                "is_notifying": is_notifying,
                "update_period": update_period,
                "user": user_instance,
                "stock": stock_instance,
            }

            stock_user_instance = StockUser(**model_data)
            stock_user_instance.save()
            
            stocks = Stock.objects.exclude(pk__in=Subquery(subquery))
            return render(request, 'stocks/index.html', {'stocks': stocks})

        except Exception as exception:
            return render(request, 'stocks/index.html', {'stocks': stocks, 'error_message': exception})
        
        

users/views.py
from django.contrib.auth.views import LoginView
from django.views.generic import ListView
from .models import User
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import UserRegisterForm
from django.contrib.auth.views import LogoutView

class UsersListView(ListView):
    model = User
    template_name = 'users/index.html'
    context_object_name = 'users'

class CustomLoginView(LoginView):
    template_name = 'users/login.html'
    success_url = reverse_lazy('stocks:index')

class CustomRegistrationView(CreateView):
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

class CustomLogoutView(LogoutView):
    template_name = 'users/login.html'

desafio_inoa/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}INOA{% endblock %}</title>
    <style>
        body { display: flex; flex-direction: column; min-height: 100vh; }
        .container { flex: 1; }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container d-flex justify-content-between">
            <div>
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url 'stocks:index' %}">INOA</a>
                {% else %}
                    <a class="navbar-brand">INOA</a>
                {% endif %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            {% if request.path == '/stocks/' %}
                                <li class="nav-item">
                                    <a class="nav-link" href="/stock_users/{{user.id}}">Carteira</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="/stocks/">Listagem</a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <span class="nav-link">Logado como: {{ user.username }}</span>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'users:logout' %}" class="nav-link">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <main class="container text-center">
        {% block content %}{% endblock %}
    </main>

    <footer class="mt-5">
        <div class="container text-center">
            <p>© 2023 INOA. Todos direitos reservados.</p>
        </div>
    </footer>

</body>
</html>

desafio_inoa/templates/stock_users/index.html
{% extends 'base.html' %}
{% load l10n %}
{% block content %}

  <div class="my-2">
    <div class="w-100 d-flex justify-content-start">
      <h1 class="mb-4">Carteira de monitoramento</h1>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Logo</th>
          <th>Nome</th>
          <th>Preço atual</th>
          <th>Preço de venda</th>
          <th>Preço de compra</th>
          <th>Notificando por email</th>
          <th>Intervalo de atualização</th>
          <th>Última atualização</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for stock in stocks %}
          <tr>
            <td><img style="height: 56px; width: 56px;" src="{{stock.stock.logo}}"/></td>
            <td>{{ stock.stock.stock }}</td>
            <td>R$ {{ stock.close|default:0|floatformat:2 }}</td>
            <td>R$ {{ stock.selling_price|floatformat:"2" }}</td>
            <td>R$ {{ stock.buying_price|floatformat:"2" }}</td>
            <td>{% if stock.is_notifying == 0 %}Não{% else %}Sim{% endif %}</td>
            <td>{{ stock.update_period }} minuto(s)</td>
            <td>{{ stock.last_price_update|date:"d/m/Y" }} às {{ stock.last_price_update|time:"H:i" }}</td>
            <td>
              <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 4px;">
                <button class="btn btn-secondary updateStockUserButton" data-toggle="modal" data-target="#updateStockUserModal" data-id="{{stock.id}}" data-selling-price="{{stock.selling_price}}" data-buying-price="{{stock.buying_price}}" data-is-notifying="{{stock.is_notifying}}" data-update-period="{{stock.update_period}}">
                  <i class="fas fa-edit"></i>
                </button>
                <button class="btn btn-primary deleteStockUserButton" data-toggle="modal" data-target="#deleteStockUserModal" data-id="{{stock.id}}">
                  <i class="fas fa-trash"></i>
                </button>
              </div>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="9">Sem informações disponíveis no momento.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="modal fade" id="deleteStockUserModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Confirmação</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form method="POST" action="{% url 'stock_users:delete' %}">
                {% csrf_token %}
  
                <div class="modal-body text-start">
                  <p>Tem certeza que deseja remover a ação do monitoramento?</p>
                </div>

                <input type="text" id="stockUser" name="stock_user" hidden>

                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </form>
        </div>
    </div>
  </div>

  <div class="modal fade" id="updateStockUserModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Atualizar</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form method="POST" action="{% url 'stock_users:update' %}">
                {% csrf_token %}
  
                <div class="modal-body text-start">
                  <div class="form-group">
                      <label for="buying_price">Preço de compra:</label>
                      <input type="text" id="buying_price" name="buying_price" id="selling_price" class="form-control" required>
                  </div>
                  <div class="form-group">
                      <label for="selling_price">Preço de venda:</label>
                      <input type="text" id="selling_price" name="selling_price" id="buying_price" class="form-control" required>
                  </div>
                  <div class="form-group">
                      <label for="update_period">Atualizar em:</label>
                      <select id="update_period" name="update_period" class="form-control" id="update_period" required>
                        <option value="">Selecione</option>
                        <option value="1">1 minuto</option>
                        <option value="5">5 minutos</option>
                        <option value="10">10 minutos</option>
                        <option value="15">15 minutos</option>
                        <option value="30">30 minutos</option>
                        <option value="60">60 minutos</option>
                      </select>
                  </div>
                  <div class="form-group">
                    <label for="is_notifying">Notificar por email:</label>
                    <select id="is_notifying" name="is_notifying" class="form-control" id="is_notifying" required>
                        <option value="">Selecione</option>
                        <option value="1">Sim</option>
                        <option value="0">Não</option>
                    </select>
                </div>

              </div>

                <input type="text" id="updateStockUser" name="updated_stock_user_id" hidden>

                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </form>
        </div>
    </div>
  </div>

  <script>

    $('#buying_price').mask("#.##0,00", {reverse: true});
    $('#selling_price').mask("#.##0,00", {reverse: true});

    $(".deleteStockUserButton").on("click", function() {
      let id = $(this).data("id")
      $("#stockUser").val('')
      $("#stockUser").val(id)
    })

    $(".updateStockUserButton").on("click", function() {
      let id = $(this).data("id")

      let selling_price = $(this).data("selling-price")
      let buying_price = $(this).data("buying-price")
      let is_notifying = $(this).data("is-notifying")
      let update_period = $(this).data("update-period")

      $("#selling_price").val(selling_price)
      $("#buying_price").val(buying_price)
      $("#is_notifying").val(is_notifying)
      $("#update_period").val(update_period)

      $("#updateStockUser").val('')
      $("#updateStockUser").val(id)

      $('#buying_price').trigger('input');
      $('#selling_price').trigger('input');
    })
  </script>

{% endblock %}

desafio_inoa/templates/stocks/index.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<div class="alert alert-danger">
  {{ error_message }}
</div>
{% endif %}

<div class="my-2">
  <div class="w-100 d-flex justify-content-start">
    <h1 class="mb-4">Listagem</h1>
  </div>
    <table class="table">
      <thead>
        <tr>
          <th>Logo</th>
          <th>Sigla</th>
          <th>Nome</th>
          <th>Setor</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for stock in stocks %}
          <tr>
            <td><img style="height: 56px; width: 56px;" src="{{stock.logo}}"/></td>
            <td>{{ stock.stock }}</td>
            <td>{{ stock.name }}</td>
            <td>{{ stock.sector }}</td>
            <td>
              <button class="btn btn-primary addStockButton" data-toggle="modal" data-target="#addStockModal" data-stock-name="{{stock.stock}}">
                  <i class="fas fa-check"></i>
              </button>
          </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="9">Sem informações disponíveis no momento.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="modal fade" id="addStockModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Monitorar</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form method="POST" action="{% url 'stocks:index' %}">
                {% csrf_token %}
                <div id="price-alert">

                </div>
                <div class="modal-body text-start">
                    <div class="form-group">
                        <label for="buying_price">Preço de compra:</label>
                        <input type="text" id="buying_price" name="buying_price" id="buying_price" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="selling_price">Preço de venda:</label>
                        <input type="text" id="selling_price" name="selling_price" id="buying_price" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="update_period">Atualizar em:</label>
                        <select id="update_period" name="update_period" class="form-control" required>
                          <option value="">Selecione</option>
                          <option value="1">1 minuto</option>
                          <option value="5">5 minutos</option>
                          <option value="10">10 minutos</option>
                          <option value="15">15 minutos</option>
                          <option value="30">30 minutos</option>
                          <option value="60">60 minutos</option>
                        </select>
                    </div>
                    <div class="form-group">
                      <label for="is_notifying">Notificar por email:</label>
                      <select id="is_notifying" name="is_notifying" class="form-control">
                          <option value="">Selecione</option>
                          <option value="1">Sim</option>
                          <option value="0">Não</option>
                      </select>
                  </div>
                  <input type="text" id="stock" name="stock" hidden>
                </div>

                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>

  $('#buying_price').mask("#.##0,00", {reverse: true});
  $('#selling_price').mask("#.##0,00", {reverse: true});

  $(".addStockButton").on("click", function() {
    let stock = $(this).data("stock-name")
    $("#stock").val('')
    $("#stock").val(stock)

    api_url = `https://brapi.dev/api/quote/list?sortBy=close&sortOrder=desc&limit=10&search=${stock}`

    $.ajax({
        url: api_url,
        method: "GET",
        dataType: "json",
        success: function(response) {
          if (response.stocks.length > 0) {
                let currentPrice = response.stocks[0].close;
                let message = `A cotação atual para essa ação é de R$ ${currentPrice.toFixed(2)}`;

                $("#price-alert").html(`<div class="alert alert-info">${message}</div>`);
            } else {

                $("#price-alert").html('<div class="alert alert-danger">Nenhuma informação encontrada.</div>');
            }
        },
        error: function(jqXHR, textStatus, errorThrown) {
            console.error("API Error:", textStatus, errorThrown);
        }
    });

});



</script>

</html>

  {% endblock %}

desafio_inoa/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
  <div style="margin-top: 150px;" class="container">
    <div class="d-flex justify-content-center align-items-center">
      <div class="card">
        <div class="card-header"><h3>Login</h3></div>
        <div class="card-body">
          <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            <div class="form-outline mb-4 text-left">
              <label class="form-label">Username</label>
              <input type="text" name="username" class="form-control" required/>
            </div>
          
            <div class="form-outline mb-4 text-left">
              <label class="form-label">Senha</label>
              <input type="password" name="password" class="form-control" required/>
            </div>
        
            <button type="submit" class="btn btn-primary btn-block mb-4">Enviar</button>
          
          </form>
        </div>
        <div class="card-footer text-center">
          <p>Não é membro? <a href="{% url 'users:register' %}">Registre-se</a></p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

desafio_inoa/templates/users/register.html
{% extends 'base.html' %}

{% block content %}

{% if form.errors %}
<div class="alert alert-danger">
    <strong>Error:</strong> Please correct the following errors.
    <ul>
        {% for field, errors in form.errors.items %}
        <li>{{ field }}: {{ errors }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<div style="margin-top: 150px;" class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header"><h3>Cadastro</h3></div>
                <div class="card-body">
                    <form method="post" action="{% url 'users:register' %}">
                        {% csrf_token %}
                        
                        <div class="form-group text-left">
                            <label>Usuário</label>
                            <input type="text" name="username" class="form-control" required>
                        </div>
                        
                        <div class="form-group text-left">
                            <label>Email</label>
                            <input type="email" name="email" class="form-control" required>
                        </div>
                        
                        <div class="form-group text-left">
                            <label>Senha</label>
                            <input type="password" name="password1" class="form-control" required>
                        </div>

                        <div class="form-group text-left">
                            <label>Confirme sua senha</label>
                            <input type="password" name="password2" class="form-control" required>
                        </div>
                        
                        <button type="submit" class="btn btn-primary btn-block">Enviar</button>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <p>Já tem uma conta? <a href="{% url 'users:login' %}">Login</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}